// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clvtzwpfrqeaoajajgfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsdnR6d3BmcnFlYW9hamFqZ2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDA4NTQsImV4cCI6MjA3MjQ3Njg1NH0.Wc9NmqKyYzmZ6UiM6UwSpRg0t4KeQ2kXkNR2qNlGxmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});